server:
        port: 9000

spring:
        application:
                name: cards
        config:
                import: optional:configserver:http://localhost:8071/
        datasource:
                url: "jdbc:mysql://localhost:3308/cardsDB"
                username: root
                password: root
        sql:
                init:
                        mode: always
        jpa:
                show-sql: true
        rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

management:
        endpoints:
                web:
                        exposure:
                                include: '*'