INSERT INTO contact_msg (name,
                         mobile_num,
                         email,
                         subject,
                         message,
                         status,
                         created_at,
                         created_by)
VALUES ('Adam',
        '2176436587',
        'zadam@gmail.com',
        'Regarding a job',
        'Wanted to join as teacher',
        'Open',
        GETDATE(),
        'DBA'),
       ('Zara',
        '3412654387',
        'zarabaig@hotmail.com',
        'Course Admission',
        'Wanted to join a course',
        'Open',
        GETDATE(),
        'DBA'),
       ('Marques',
        '8547643673',
        'kmarques@yahoo.com',
        'Course Review',
        'Review of Development course',
        'Open',
        GETDATE(),
        'DBA'),
       ('Shyam',
        '4365328776',
        'gshyam@gmail.com',
        'Admission Query',
        'Need to talk about admission',
        'Open',
        GETDATE(),
        'DBA'),
       ('John',
        '5465765453',
        'doejohn@gmail.com',
        'Holiday Query',
        'Query on upcoming holidays',
        'Open',
        GETDATE(),
        'DBA'),
       ('Taniya Bell',
        '3987463827',
        'belltaniya@gmail.com',
        'Child Scholarship',
        'Can my child get scholarship?',
        'Open',
        GETDATE(),
        'DBA'),
       ('Willie Lara',
        '4568764801',
        '476lara@gmail.com',
        'Need Admission',
        'My son need an admission',
        'Open',
        GETDATE(),
        'DBA'),
       ('Jonathan Parsons',
        '4321768902',
        'jonathan.parsons@gmail.com',
        'Course feedback',
        'Music course is good',
        'Open',
        GETDATE(),
        'DBA'),
       ('Cloe Rubio',
        '9854438719',
        'rubio987@gmail.com',
        'Correct Date of Birth',
        'My Child DOB needs to be corrected',
        'Open',
        GETDATE(),
        'DBA'),
       ('Camilla Stein',
        '6545433254',
        'camillas@gmail.com',
        'Transport Query',
        'Is Transport provided?',
        'Open',
        GETDATE(),
        'DBA'),
       ('Lizeth Gross',
        '4678783434',
        'grossliz@yahoo.com',
        'Progress report',
        'Please send progress report',
        'Open',
        GETDATE(),
        'DBA'),
       ('Yael Howe',
        '1243563254',
        'howeyael@gmail.com',
        'Certificate Query',
        'Need Certificate hard copy',
        'Open',
        GETDATE(),
        'DBA'),
       ('Ian Moreno',
        '2312231223',
        'moreno.ian@gmail.com',
        'Food feedback',
        'Food quality can be improved',
        'Open',
        GETDATE(),
        'DBA'),
       ('Desirae Ibarra',
        '3445235667',
        'ibarrades@gmail.com',
        'Traffic Complaint',
        'Traffic around school can be controlled',
        'Open',
        GETDATE(),
        'DBA'),
       ('Oswaldo Jarvis',
        '4556121265',
        'jarvissmile@hotmail.com',
        'Study Tour',
        'Study tour details needed',
        'Open',
        GETDATE(),
        'DBA'),
       ('Miah Perkins',
        '2367784512',
        'perkinsmiah@hotmail.com',
        'Vaccination Support',
        'Vaccination center in the school',
        'Open',
        GETDATE(),
        'DBA'),
       ('Zion Bolton',
        '8990678900',
        'boltzion@gmail.com',
        'Course fees',
        'Pls share fees of music course',
        'Open',
        GETDATE(),
        'DBA'),
       ('Dominik Tanner',
        '4556127834',
        'tannerdominik@gmail.com',
        'Games schedule',
        'Provide Summer games schedule',
        'Open',
        GETDATE(),
        'DBA');
