services:
        accounts:
                image: mayasage/accounts:s1
                container_name: accounts-microservice
                ports:
                        - "8080:8080"
                deploy:
                        resources:
                                limits:
                                        memory: 700m
                networks:
                        - easybank
        loans:
                image: mayasage/loans:s1
                container_name: loans-microservice
                ports:
                        - "8090:8090"
                deploy:
                        resources:
                                limits:
                                        memory: 700m
                networks:
                        - easybank
        cards:
                image: mayasage/cards:s1
                container_name: cards-microservice
                ports:
                        - "9000:9000"
                deploy:
                        resources:
                                limits:
                                        memory: 700m
                networks:
                        - easybank

networks:
        easybank:
                driver: bridge