services:
        mysql:
                image: mysql:8.0
                container_name: vlad-mysql
                restart: unless-stopped
                environment:
                        MYSQL_DATABASE: vlad
                        MYSQL_ROOT_PASSWORD: thunder_DBMS1
                ports:
                        - "3306:3306"
                volumes:
                        - mysql-data:/var/lib/mysql

volumes:
        mysql-data:
